# Generated by Django 5.2.17 on 2026-08-09 16:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('principio_ativo', models.CharField(blank=True, max_length=160)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicamentos', to='core.clinica')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Apresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentracao', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=120)),
                ('quantidade_mg', models.DecimalField(decimal_places=3, help_text='Quantidade total em mg por frasco/apresentação.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('ativa', models.BooleanField(default=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apresentacoes', to='core.medicamento')),
            ],
            options={
                'ordering': ['medicamento__nome', 'quantidade_mg'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('administrador', 'Administrador'), ('farmaceutico', 'Farmacêutico'), ('auxiliar', 'Auxiliar'), ('enfermagem', 'Enfermagem'), ('gestor', 'Gestor'), ('leitura', 'Somente leitura')], default='leitura', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='perfis', to='core.clinica')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_oncologia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('diagnostico_referencia', models.CharField(blank=True, max_length=180)),
                ('intervalo_dias', models.PositiveSmallIntegerField(default=21)),
                ('total_ciclos', models.PositiveSmallIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos', to='core.clinica')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('diagnostico', models.CharField(blank=True, max_length=200)),
                ('data_inicio', models.DateField()),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('altura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro/não informado')], max_length=1)),
                ('tfg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='core.clinica')),
                ('protocolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='core.protocolo')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclos', models.CharField(default='1', help_text='Ex.: 1, 2, 3, 4', max_length=120)),
                ('dias_ciclo', models.CharField(default='1', help_text='Ex.: 1, 15', max_length=120)),
                ('tipo_dose', models.CharField(choices=[('fixa', 'Dose fixa (mg)'), ('mg_kg', 'mg/kg'), ('mg_m2', 'mg/m²')], default='mg_m2', max_length=10)),
                ('dose_valor', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('apresentacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.apresentacao')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.protocolo')),
            ],
        ),
        migrations.CreateModel(
            name='SessaoTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('ciclo', models.PositiveSmallIntegerField(default=1)),
                ('dia_ciclo', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='agendada', max_length=12)),
                ('observacoes', models.CharField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='core.clinica')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='core.paciente')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='core.protocolo')),
            ],
            options={
                'ordering': ['data_hora'],
            },
        ),
        migrations.AddConstraint(
            model_name='medicamento',
            constraint=models.UniqueConstraint(fields=('clinica', 'nome'), name='medicamento_nome_por_clinica'),
        ),
        migrations.AddConstraint(
            model_name='sessaotratamento',
            constraint=models.UniqueConstraint(fields=('clinica', 'paciente', 'data_hora', 'ciclo', 'dia_ciclo'), name='sessao_sem_duplicidade_exata'),
        ),
    ]
