# Generated by Django 5.2.17 on 2026-08-10 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=60)),
                ('data_validade', models.DateField()),
                ('quantidade_inicial', models.PositiveIntegerField(default=0)),
                ('quantidade_atual', models.PositiveIntegerField(default=0)),
                ('estoque_minimo', models.PositiveIntegerField(default=5)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('apresentacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='core.apresentacao')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='core.clinica')),
            ],
            options={
                'ordering': ['data_validade', 'apresentacao__medicamento__nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada / Recebimento'), ('saida', 'Saída / Aplicação'), ('perda', 'Perda / Descarte'), ('ajuste', 'Ajuste de Inventário'), ('reserva', 'Reserva')], max_length=20)),
                ('quantidade', models.IntegerField(help_text='Positivo para entradas, negativo para saídas.')),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque', to='core.clinica')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='core.lote')),
                ('sessao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque', to='core.sessaotratamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('clinica', 'apresentacao', 'numero_lote'), name='lote_unico_por_apresentacao_clinica'),
        ),
    ]
