# Generated by Django 5.2.17 on 2026-08-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_registroauditoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='tfg',
        ),
        migrations.AddField(
            model_name='paciente',
            name='ciclos_previstos',
            field=models.PositiveSmallIntegerField(default=1, help_text='Quantidade de ciclos previstos para o tratamento'),
        ),
    ]
