# Generated by Django 5.2.17 on 2026-08-11 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_paciente_tfg_paciente_ciclos_previstos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente de aprovação'), ('aprovado', 'Aprovado'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], default='rascunho', max_length=12)),
                ('fornecedor', models.CharField(blank=True, max_length=120)),
                ('observacao', models.CharField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('data_recebimento', models.DateTimeField(blank=True, null=True)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='core.clinica')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('quantidade_recebida', models.PositiveIntegerField(default=0)),
                ('custo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('apresentacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.apresentacao')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedidocompra')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pedidocompra',
            constraint=models.UniqueConstraint(fields=('clinica', 'numero'), name='pedido_clinica_numero_unico'),
        ),
    ]
