# Generated by Django 5.2.17 on 2026-08-11 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedidocompra_itempedidocompra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_transito', 'Em trânsito'), ('recebida', 'Recebida'), ('cancelada', 'Cancelada')], default='rascunho', max_length=12)),
                ('observacao', models.CharField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_recebimento', models.DateTimeField(blank=True, null=True)),
                ('clinica_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recebidas', to='core.clinica')),
                ('clinica_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to='core.clinica')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('quantidade_recebida', models.PositiveIntegerField(default=0)),
                ('apresentacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.apresentacao')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.transferencia')),
            ],
        ),
        migrations.AddConstraint(
            model_name='transferencia',
            constraint=models.UniqueConstraint(fields=('clinica_origem', 'numero'), name='transferencia_origem_numero_unico'),
        ),
    ]
