# Generated by Django 5.2.17 on 2026-08-11 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transferencia_itemtransferencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('papel_solicitado', models.CharField(choices=[('administrador', 'Administrador'), ('farmaceutico', 'Farmacêutico'), ('auxiliar', 'Auxiliar'), ('enfermagem', 'Enfermagem'), ('gestor', 'Gestor'), ('leitura', 'Somente leitura')], max_length=20)),
                ('justificativa', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=12)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('data_analise', models.DateTimeField(blank=True, null=True)),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_acesso', to='core.clinica')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
