# Generated by Django 5.2.17 on 2026-08-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_importacaoarquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaotratamento',
            name='motivo',
            field=models.CharField(blank=True, help_text='Motivo de falta ou cancelamento, quando aplicável.', max_length=300),
        ),
        migrations.AlterField(
            model_name='sessaotratamento',
            name='status',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('faltou', 'Faltou / Não compareceu')], default='agendada', max_length=12),
        ),
    ]
