# Generated by Django 5.2.17 on 2026-08-11 04:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sessao_faltou_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apresentacao',
            name='condicoes_armazenamento',
            field=models.CharField(blank=True, help_text='Ex.: Refrigerar entre 2 °C e 8 °C.', max_length=200),
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='estabilidade_apos_abertura',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Estabilidade após abertura/reconstituição. Deixe vazio se não houver valor de referência cadastrado.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='fonte_referencia',
            field=models.CharField(blank=True, help_text='Fonte/bula/referência da estabilidade.', max_length=200),
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='observacoes_estabilidade',
            field=models.CharField(blank=True, help_text='Observações de manipulação/reconstituição.', max_length=300),
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='unidade_estabilidade',
            field=models.CharField(choices=[('horas', 'Horas'), ('dias', 'Dias')], default='horas', max_length=10),
        ),
    ]
