# Generated by Django 5.2.17 on 2026-08-11 05:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_apresentacao_estabilidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SobraReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_mg', models.DecimalField(decimal_places=3, help_text='Quantidade de sobra em mg.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('data_abertura', models.DateTimeField()),
                ('limite_estabilidade', models.DateTimeField(blank=True, help_text='Calculado a partir da estabilidade cadastrada da apresentação.', null=True)),
                ('condicoes_armazenamento', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reutilizada', 'Reutilizada'), ('expirada', 'Expirada'), ('descartada', 'Descartada')], default='disponivel', max_length=12)),
                ('data_reutilizacao', models.DateTimeField(blank=True, null=True)),
                ('motivo_descarte', models.CharField(blank=True, max_length=300)),
                ('data_descarte', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('apresentacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sobras_reais', to='core.apresentacao')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sobras_reais', to='core.clinica')),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sobras_reais', to='core.lote')),
                ('paciente_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sobras_recebidas', to='core.paciente')),
                ('paciente_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sobras_geradas', to='core.paciente')),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
    ]
