# Generated by Django 5.2.17 on 2026-08-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sobra_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaoarquivo',
            name='tipo',
            field=models.CharField(choices=[('medicamentos', 'Medicamentos'), ('gmed', 'GMED'), ('transferencias', 'Transferências')], default='medicamentos', help_text='Origem/destino da importação (catálogo, GMED ou transferências de Ji-Paraná).', max_length=20),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='importada',
            field=models.BooleanField(default=False, help_text='Verdadeiro quando a transferência veio de importação de planilha (Ji-Paraná).'),
        ),
    ]
