# Generated by Django 5.2.17 on 2026-08-11 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_importacao_tipo_transferencia_importada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtransferencia',
            name='status_reconciliacao',
            field=models.CharField(choices=[('conforme', 'Conforme'), ('nao_fotografado', 'Não fotografado'), ('conferencia_manual', 'Conferência manual'), ('divergencia_produto', 'Divergência de produto'), ('divergencia_apresentacao', 'Divergência de apresentação'), ('divergencia_lote', 'Divergência de lote'), ('divergencia_quantidade', 'Divergência de quantidade'), ('validade_nao_identificada', 'Validade não identificada'), ('validade_critica', 'Validade crítica'), ('item_nao_previsto', 'Item não previsto'), ('possivel_duplicidade', 'Possível duplicidade'), ('foto_insuficiente', 'Foto insuficiente')], default='nao_fotografado', help_text='Status da conferência automatizada (mantido em sincronia com a reconciliação).', max_length=28),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='data_relatorio',
            field=models.DateField(blank=True, help_text='Data de emissão do relatório de transferência.', null=True),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='hash_relatorio',
            field=models.CharField(blank=True, help_text='SHA-256 do arquivo do relatório (evita importação duplicada).', max_length=64),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='referencia_externa',
            field=models.CharField(blank=True, help_text='Número identificador do documento / referência externa.', max_length=120),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='relatorio_arquivo',
            field=models.FileField(blank=True, help_text='PDF original do relatório de transferência (Ji-Paraná).', null=True, upload_to='transferencias/relatorios/'),
        ),
        migrations.AddField(
            model_name='transferencia',
            name='status_conferencia',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('relatorio_importado', 'Relatório importado'), ('em_transito', 'Em trânsito'), ('aguardando_recebimento', 'Aguardando recebimento'), ('em_conferencia', 'Em conferência'), ('pendencia_manual', 'Pendência manual'), ('divergencia', 'Divergência'), ('pronta_para_aprovacao', 'Pronta para aprovação'), ('aprovada', 'Aprovada'), ('integrada_ao_estoque', 'Integrada ao estoque'), ('cancelada', 'Cancelada')], default='rascunho', help_text='Estado do fluxo de conferência automatizada do recebimento.', max_length=30),
        ),
        migrations.CreateModel(
            name='DivergenciaTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('produto', 'Produto diferente'), ('apresentacao', 'Apresentação diferente'), ('lote', 'Lote diferente'), ('quantidade', 'Quantidade diferente'), ('validade', 'Validade'), ('item_extra', 'Item não previsto no relatório'), ('item_ausente', 'Item previsto ausente'), ('foto_insuficiente', 'Foto insuficiente'), ('duplicidade', 'Possível duplicidade de evidência')], max_length=20)),
                ('severidade', models.CharField(choices=[('informativa', 'Informativa'), ('media', 'Média'), ('critica', 'Crítica')], default='media', max_length=12)),
                ('valor_esperado', models.CharField(blank=True, max_length=300)),
                ('valor_observado', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('resolvida', 'Resolvida'), ('ignorada', 'Ignorada')], default='pendente', max_length=12)),
                ('resolucao', models.CharField(blank=True, max_length=500)),
                ('resolvida_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divergencias', to='core.itemtransferencia')),
                ('resolvida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divergencias', to='core.transferencia')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliacaoItemTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_observado', models.CharField(blank=True, max_length=80)),
                ('validade_observada', models.DateField(blank=True, null=True)),
                ('quantidade_observada', models.PositiveIntegerField(blank=True, null=True)),
                ('match_produto', models.BooleanField(null=True)),
                ('match_lote', models.BooleanField(null=True)),
                ('match_quantidade', models.BooleanField(null=True)),
                ('status_validade', models.CharField(blank=True, help_text='ok|critica|desconhecida|vencida', max_length=20)),
                ('status_final', models.CharField(choices=[('conforme', 'Conforme'), ('nao_fotografado', 'Não fotografado'), ('conferencia_manual', 'Conferência manual'), ('divergencia_produto', 'Divergência de produto'), ('divergencia_apresentacao', 'Divergência de apresentação'), ('divergencia_lote', 'Divergência de lote'), ('divergencia_quantidade', 'Divergência de quantidade'), ('validade_nao_identificada', 'Validade não identificada'), ('validade_critica', 'Validade crítica'), ('item_nao_previsto', 'Item não previsto'), ('possivel_duplicidade', 'Possível duplicidade'), ('foto_insuficiente', 'Foto insuficiente')], default='nao_fotografado', max_length=28)),
                ('confianca_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('anotacoes', models.CharField(blank=True, max_length=500)),
                ('revisado_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliacao', to='core.itemtransferencia')),
                ('produto_observado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliacoes', to='core.apresentacao')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferenciaEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='Foto original da embalagem (nunca substituída).', upload_to='transferencias/evidencias/')),
                ('hash_arquivo', models.CharField(help_text='SHA-256 do arquivo.', max_length=64)),
                ('qualidade', models.DecimalField(blank=True, decimal_places=2, help_text='Score de qualidade visual (0 a 1).', max_digits=4, null=True)),
                ('status', models.CharField(choices=[('nova', 'Nova (aguardando extração)'), ('processando', 'Processando'), ('extraida', 'Extraída'), ('falhou', 'Falhou'), ('requer_revisao', 'Requere revisão manual')], default='nova', max_length=20)),
                ('suspeita_duplicidade', models.BooleanField(default=False, help_text='Marcado quando o hash indica possível envio repetido (nunca exclui automaticamente).')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, help_text='Item provável ao qual a foto pertence (vínculo manual ou por semelhança).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='core.itemtransferencia')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='core.transferencia')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ExtracaoEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(blank=True, max_length=200)),
                ('principio_ativo', models.CharField(blank=True, max_length=200)),
                ('apresentacao', models.CharField(blank=True, max_length=200)),
                ('lote', models.CharField(blank=True, max_length=80)),
                ('validade', models.DateField(blank=True, null=True)),
                ('fabricacao', models.DateField(blank=True, null=True)),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('codigo_gs1', models.CharField(blank=True, help_text='GTIN/GS1 quando decodificado.', max_length=64)),
                ('lote_gs1', models.CharField(blank=True, max_length=80)),
                ('validade_gs1', models.DateField(blank=True, null=True)),
                ('confianca_produto', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('confianca_lote', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('confianca_validade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('confianca_quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('engine', models.CharField(default='manual', help_text='Provider/modelo usado.', max_length=60)),
                ('versao', models.CharField(default='1', max_length=40)),
                ('resultado_bruto', models.JSONField(blank=True, default=dict)),
                ('requer_revisao', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('extraido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracoes', to='core.transferenciaevidencia')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AliasMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Nome/descrição como aparece no relatório de transferência.', max_length=160)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases_medicamento', to='core.clinica')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='core.medicamento')),
            ],
            options={
                'ordering': ['alias'],
                'constraints': [models.UniqueConstraint(fields=('clinica', 'alias'), name='alias_medicamento_unico_por_clinica')],
            },
        ),
    ]
