# Generated by Django 5.2.17 on 2026-08-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_conferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtransferencia',
            name='status_reconciliacao',
            field=models.CharField(choices=[('conforme', 'Conforme'), ('nao_fotografado', 'Não fotografado'), ('conferencia_manual', 'Conferência manual'), ('divergencia_produto', 'Divergência de produto'), ('divergencia_apresentacao', 'Divergência de apresentação'), ('divergencia_lote', 'Divergência de lote'), ('divergencia_quantidade', 'Divergência de quantidade'), ('validade_nao_identificada', 'Validade não identificada'), ('validade_critica', 'Validade crítica'), ('divergencia_validade', 'Validade divergente/vencida'), ('item_nao_previsto', 'Item não previsto'), ('possivel_duplicidade', 'Possível duplicidade'), ('foto_insuficiente', 'Foto insuficiente')], default='nao_fotografado', help_text='Status da conferência automatizada (mantido em sincronia com a reconciliação).', max_length=28),
        ),
        migrations.AlterField(
            model_name='reconciliacaoitemtransferencia',
            name='status_final',
            field=models.CharField(choices=[('conforme', 'Conforme'), ('nao_fotografado', 'Não fotografado'), ('conferencia_manual', 'Conferência manual'), ('divergencia_produto', 'Divergência de produto'), ('divergencia_apresentacao', 'Divergência de apresentação'), ('divergencia_lote', 'Divergência de lote'), ('divergencia_quantidade', 'Divergência de quantidade'), ('validade_nao_identificada', 'Validade não identificada'), ('validade_critica', 'Validade crítica'), ('divergencia_validade', 'Validade divergente/vencida'), ('item_nao_previsto', 'Item não previsto'), ('possivel_duplicidade', 'Possível duplicidade'), ('foto_insuficiente', 'Foto insuficiente')], default='nao_fotografado', max_length=28),
        ),
    ]
