# Generated by Django 5.2.17 on 2026-08-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_divergencia_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtransferencia',
            name='lote_esperado',
            field=models.CharField(blank=True, help_text='Lote informado no relatório de transferência (Ji-Paraná).', max_length=80),
        ),
        migrations.AddField(
            model_name='itemtransferencia',
            name='tipo_insumo',
            field=models.CharField(blank=True, help_text='Seção do relatório: Medicamento, Material de Enfermagem, Solução etc.', max_length=60),
        ),
    ]
