# Generated by Django 5.2.17 on 2026-08-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_lote_esperado_tipo_insumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroauditoria',
            name='hash_anterior',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='hash_registro',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
