# Generated by Django 5.2.17 on 2026-08-13 03:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_backfill_auditoria_hashes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(default='Centro de Oncologia', max_length=120)),
                ('periodo_padrao_dias', models.PositiveSmallIntegerField(choices=[(7, 'Últimos/próximos 7 dias'), (14, '14 dias'), (30, '30 dias')], default=7)),
                ('densidade_tabela', models.CharField(choices=[('padrao', 'Padrão'), ('compacta', 'Compacta')], default='padrao', max_length=10)),
                ('alertar_estoque_minimo', models.BooleanField(default=True)),
                ('alertar_validade_30_dias', models.BooleanField(default=True)),
                ('alertar_validacao_pendente', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_clinica_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao', to='core.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='MedicacaoOral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('quimioterapia', 'Quimioterapia oral'), ('hormonioterapia', 'Hormonioterápico'), ('suporte', 'Medicação de suporte'), ('outros', 'Outros')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('quantidade_ciclos', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('ciclo_atual', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('intervalo_dias', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('renovacao_pedido_meses', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('solicitar_guia_antes_dias', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('estrategia_aquisicao', models.CharField(choices=[('lista_programada', 'Lista programada'), ('compra_por_guia', 'Compra individual por guia')], default='lista_programada', max_length=20)),
                ('motivo_prioridade', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('prevista', 'Prevista'), ('aguardando_documento', 'Aguardando documento'), ('pronta', 'Pronta para dispensação'), ('pausada', 'Pausada'), ('concluida', 'Concluída')], default='prevista', max_length=24)),
                ('observacoes', models.CharField(blank=True, max_length=500)),
                ('revisado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicacoes_orais', to='core.clinica')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos_orais', to='core.medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicacoes_orais', to='core.paciente')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicacoes_orais_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_inicio', 'paciente__nome'],
                'constraints': [models.UniqueConstraint(fields=('clinica', 'paciente', 'medicamento', 'data_inicio'), name='medicacao_oral_sem_duplicidade_exata')],
            },
        ),
    ]
