# Generated by Django 5.2.17 on 2026-08-13 03:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_configuracaoclinica_medicacaooral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='medicacaooral',
            constraint=models.CheckConstraint(condition=models.Q(('ciclo_atual__lte', models.F('quantidade_ciclos'))), name='medicacao_oral_ciclo_dentro_do_planejado'),
        ),
    ]
