# Generated by Django 5.2.17 on 2026-08-14 02:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_medicacaooral_medicacao_oral_ciclo_dentro_do_planejado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicacaooral',
            name='medicacao_oral_sem_duplicidade_exata',
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='observacoes',
            field=models.CharField(blank=True, help_text='Informações adicionais sobre esta apresentação.', max_length=500),
        ),
        migrations.AddField(
            model_name='lote',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='observacoes',
            field=models.CharField(blank=True, help_text='Informações adicionais sobre o lote e sua armazenagem.', max_length=500),
        ),
        migrations.AddField(
            model_name='medicacaooral',
            name='apresentacao',
            field=models.ForeignKey(blank=True, help_text='Apresentação prevista para compra/dispensação, quando definida.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos_orais', to='core.apresentacao'),
        ),
        migrations.AddField(
            model_name='medicacaooral',
            name='dose_prescrita',
            field=models.CharField(blank=True, help_text='Texto transcrito da prescrição; exige conferência profissional.', max_length=120),
        ),
        migrations.AddField(
            model_name='medicacaooral',
            name='motivo_alteracao',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='medicacaooral',
            name='posologia',
            field=models.CharField(blank=True, help_text='Posologia transcrita da prescrição; exige conferência profissional.', max_length=240),
        ),
        migrations.AddField(
            model_name='medicacaooral',
            name='quantidade_por_ciclo',
            field=models.PositiveIntegerField(default=1, help_text='Unidades de estoque da apresentação por ciclo para planejamento de compra.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='medicacaooral',
            name='substitui',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versoes_posteriores', to='core.medicacaooral'),
        ),
        migrations.AddField(
            model_name='medicacaooral',
            name='vigente',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='observacoes',
            field=models.CharField(blank=True, help_text='Informações administrativas ou farmacêuticas adicionais para revisão humana.', max_length=500),
        ),
        migrations.AddField(
            model_name='sessaotratamento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='medicacaooral',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente', True)), fields=('clinica', 'paciente', 'medicamento', 'data_inicio'), name='medicacao_oral_vigente_sem_duplicidade_exata'),
        ),
    ]
